### ISSUE TITLE
CH11 problem.

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/simh#3]
Making notes so I can ask people for advice.

**Comment by bictorv** [comment]
A Chaos packet is indeed max 504 bytes (or 4032 bits if you read MIT AIM 628), and on some media (incl CHUDP, excl Ethernet) a "hardware trailer" of 6 bytes is appended. CHUDP pre-pends a 4-byte header. So 514 would be the max for a CHUDP pkt.

**Comment by bictorv** [comment]
> A Chaos packet is indeed max 504 bytes (or 4032 bits if you read MIT AIM 628), and on some media (incl CHUDP, excl Ethernet) a "hardware trailer" of 6 bytes is appended. CHUDP pre-pends a 4-byte header. So 514 would be the max for a CHUDP pkt.

Plus 48 bits of header, so 510 bytes. Plus trailer and CHUDP header.

**Comment by larsbrinkhoff** [comment]
It seems to work fine with VAX and PDP-11 software.  I haven't tested ITS.

We have a PDP-10 I/O bus CH10 in the works.  It's a slightly modified CH11.

There were a Qbus version of CH11.  Comments in MINITS say it worked a little bit differently from CH11, but as far as I can see the actual code is exactly the same.

**Comment by bictorv** [comment]
In other news, the [chaosnet-bridge](https://github.com/bictorv/chaosnet-bridge) now supports Chaosnet-over-TLS, which is more reliable, works without a stable IP, and actually seems faster (ymmv, of course).
